# Generated by Django 4.1.5 on 2023-01-11 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='content',
            new_name='map_requirements',
        ),
        migrations.AddField(
            model_name='contact',
            name='plot_size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='road_direction',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
